export type ProductCatalogEntry={name:string;supplier:"Infra"|"Butinox"|"Jotun";image:string;aliases:string[];category:string};
export const PRODUCT_CATALOG:ProductCatalogEntry[]=[
{name:"Infra Nordlys",supplier:"Infra",image:"/products/Infra Nordlys.jpg",aliases:["INFRA NORDLYS"],category:"Maling / Dekkbeis / Beis"},
{name:"Infra Premium Residence",supplier:"Infra",image:"/products/Infra Premium Residence.jpg",aliases:["INFRA PREMIUM RES","INFRA PREM RES"],category:"Maling / Dekkbeis / Beis"},
{name:"Infra Superior",supplier:"Infra",image:"/products/Infra Superior.jpg",aliases:["INFRA SUPERIOR"],category:"Maling / Dekkbeis / Beis"},
{name:"Infra Oljebeis",supplier:"Infra",image:"https://www.obsbygg.no/cdn-cgi/image/quality=80,width=900,format=auto/globalassets/productimages/506086_7025180674486_.jpg?ref=74833F86C8",aliases:["INFRA OLJEBEIS"],category:"Maling / Dekkbeis / Beis"},
{name:"Infra Superior Vindu / Dør",supplier:"Infra",image:"https://www.obsbygg.no/cdn-cgi/image/quality=80,width=900,format=auto/globalassets/productimages/1104275_7025180748262_1.jpg?ref=C5523443FA",aliases:["INFRA SUPERIOR VINDU","INFRA SUPERIOR DØR"],category:"Vindu / Dør"},
{name:"Infra Murmaling",supplier:"Infra",image:"https://www.obsbygg.no/cdn-cgi/image/quality=80,width=900,format=auto/globalassets/productimages/542951_7025180676954_.jpg?ref=6A0DF12089",aliases:["INFRA MURMALING"],category:"Murmaling"},
{name:"Infra Oljedekkbeis",supplier:"Infra",image:"https://www.obsbygg.no/cdn-cgi/image/quality=80,width=900,format=auto/globalassets/productimages/542827_7025180676732_1.jpg?ref=0CBDB41588",aliases:["INFRA OLJEDEKKBEIS"],category:"Maling / Dekkbeis / Beis"},
{name:"Infra Oljemaling",supplier:"Infra",image:"https://www.obsbygg.no/cdn-cgi/image/quality=80,width=900,format=auto/globalassets/productimages/597412_7025180676848_1.jpg?ref=06BCC756B6",aliases:["INFRA OLJEMALING"],category:"Maling / Dekkbeis / Beis"},
{name:"Butinox Futura 16",supplier:"Butinox",image:"/products/Butinox Futura 16.jpg",aliases:["BX FUTURA DEKKB","BUTINOX FUTURA 16"],category:"Maling / Dekkbeis / Beis"},
{name:"Butinox Futura Matt",supplier:"Butinox",image:"/products/Butinox Futura Matt.jpg",aliases:["BX FUTURA MATT","BUTINOX FUTURA MATT"],category:"Maling / Dekkbeis / Beis"},
{name:"Butinox Futura Selvrensende 12",supplier:"Butinox",image:"/products/Butinox Futura Selvrensende 12.jpg",aliases:["BX FUTURA SELV","BUTINOX FUTURA SELV"],category:"Maling / Dekkbeis / Beis"},
{name:"Butinox Futura Maling",supplier:"Butinox",image:"https://www.obsbygg.no/cdn-cgi/image/quality=80,width=900,format=auto/globalassets/productimages/1049928_7031157800888_.jpg?ref=0A2C37A7A3",aliases:["BUTINOX FUTURA MALING","BX FUTURA MALING"],category:"Maling / Dekkbeis / Beis"},
{name:"Butinox Futura Dekkbeis",supplier:"Butinox",image:"https://www.obsbygg.no/cdn-cgi/image/quality=80,width=900,format=auto/globalassets/productimages/1049820_7031152400199_1.jpg?ref=23C70D4332",aliases:["BUTINOX FUTURA DEKKBEIS","BX FUTURA DEKKBEIS"],category:"Maling / Dekkbeis / Beis"},
{name:"Butinox Oljedekkbeis",supplier:"Butinox",image:"https://www.obsbygg.no/cdn-cgi/image/quality=80,width=900,format=auto/globalassets/productimages/913355_7031157808693_1.jpg?ref=AE4D96025C",aliases:["BUTINOX OLJEDEKKBEIS","BX OLJEDEKKBEIS"],category:"Maling / Dekkbeis / Beis"},
{name:"Butinox Futura Selvrensende Grunnmur",supplier:"Butinox",image:"https://www.obsbygg.no/cdn-cgi/image/quality=80,width=900,format=auto/globalassets/productimages/1102509_7029350270492_.jpg?ref=000DE4989B",aliases:["FUTURA SELVRENSENDE GRUNNMUR","BUTINOX FUTURA GRUNNMUR"],category:"Murmaling"},
{name:"Butinox Futura Selvrensende Vindu og Dør",supplier:"Butinox",image:"https://www.obsbygg.no/cdn-cgi/image/quality=80,width=900,format=auto/globalassets/productimages/1013093_7031157809195_1.jpg?ref=1856569872",aliases:["FUTURA SELVRENSENDE VINDU","BUTINOX FUTURA VINDU"],category:"Vindu / Dør"},
{name:"Drygolin Nordic Extreme",supplier:"Jotun",image:"/products/Drygolin Nordic Extreme.jpg",aliases:["DRYG NORDIC EX","DRYGOLIN NORDIC EXTREME"],category:"Maling / Dekkbeis / Beis"},
{name:"Drygolin Optimal",supplier:"Jotun",image:"/products/Drygolin Optimal.jpg",aliases:["DRYGOLIN OPTIMAL"],category:"Maling / Dekkbeis / Beis"},
{name:"Drygolin Power Clean",supplier:"Jotun",image:"/products/Drygolin Power Clean.jpg",aliases:["DRYG POWER CLEAN","DRYGOLIN POWER CLEAN"],category:"Maling / Dekkbeis / Beis"},
{name:"Drygolin Nordic Extreme Vindu / Dør",supplier:"Jotun",image:"https://www.obsbygg.no/cdn-cgi/image/quality=80,width=900,format=auto/globalassets/productimages/512913_7029350188803_1.jpg?ref=E6290A52C3",aliases:["NORDIC EXTREME VINDU","DRYGOLIN NORDIC VINDU"],category:"Vindu / Dør"},
{name:"Drygolin Vindu og Dørmaling",supplier:"Jotun",image:"https://www.obsbygg.no/cdn-cgi/image/quality=80,width=900,format=auto/globalassets/productimages/260032_7029350008378_1.jpg?ref=2766A93D8D",aliases:["DRYGOLIN VINDU OG DØR","DRYGOLIN VINDU DØR"],category:"Vindu / Dør"},
{name:"Drygolin Pluss Oljedekkbeis",supplier:"Jotun",image:"https://www.obsbygg.no/cdn-cgi/image/quality=80,width=900,format=auto/globalassets/productimages/914519_7029350249399_1.jpg?ref=4C381DFC89",aliases:["DRYGOLIN PLUSS OLJEDEKKBEIS"],category:"Maling / Dekkbeis / Beis"},
{name:"Drygolin Pluss Oljemaling",supplier:"Jotun",image:"https://www.obsbygg.no/cdn-cgi/image/quality=80,width=900,format=auto/globalassets/productimages/234253_7029350006299_1.jpg?ref=217D7FC5C1",aliases:["DRYGOLIN PLUSS OLJEMALING"],category:"Maling / Dekkbeis / Beis"},
{name:"Drygolin Oljedekkbeis",supplier:"Jotun",image:"https://www.obsbygg.no/cdn-cgi/image/quality=80,width=900,format=auto/globalassets/productimages/914510_7029350249498_1.jpg?ref=18AB74C856",aliases:["DRYGOLIN OLJEDEKKBEIS"],category:"Maling / Dekkbeis / Beis"},
{name:"Drygolin Oljemaling",supplier:"Jotun",image:"https://www.obsbygg.no/cdn-cgi/image/quality=80,width=900,format=auto/globalassets/productimages/914516_7029350249436_1.jpg?ref=A09CB4362C",aliases:["DRYGOLIN OLJEMALING"],category:"Maling / Dekkbeis / Beis"},
{name:"Trebitt Oljebeis",supplier:"Jotun",image:"https://www.obsbygg.no/cdn-cgi/image/quality=80,width=900,format=auto/globalassets/productimages/1017080_7029350261735_.jpg?ref=A311889DBE",aliases:["TREBITT OLJEBEIS"],category:"Maling / Dekkbeis / Beis"},
{name:"Trebitt Matt Oljebeis",supplier:"Jotun",image:"https://www.obsbygg.no/cdn-cgi/image/quality=80,width=900,format=auto/globalassets/productimages/1053921_7029350261728_.jpg?ref=C42BC0F2DF",aliases:["TREBITT MATT OLJEBEIS"],category:"Maling / Dekkbeis / Beis"},
{name:"Drytech Murmaling",supplier:"Jotun",image:"https://www.obsbygg.no/cdn-cgi/image/quality=80,width=900,format=auto/globalassets/productimages/325579_7029350155102_.jpg?ref=3AE08BDDF9",aliases:["DRYTECH MURMALING"],category:"Murmaling"},
{name:"Mur Original Akryl",supplier:"Jotun",image:"https://www.obsbygg.no/cdn-cgi/image/quality=80,width=900,format=auto/globalassets/productimages/325599_7029350154884_.jpg?ref=2B1E918A89",aliases:["MUR ORIGINAL AKRYL"],category:"Murmaling"}
];
const norm=(s:string)=>s.toUpperCase().replace(/[^A-ZÆØÅ0-9]+/g," ").replace(/\s+/g," ").trim();
export function catalogEntry(product:string,rawName=""){const hay=norm(`${product} ${rawName}`);return PRODUCT_CATALOG.find(e=>[e.name,...e.aliases].some(a=>hay.includes(norm(a))));}
