import { ensureSchema, sql } from './db';
import { catalogEntry } from '../product-catalog';

const decodeHtml=(s:string)=>s.replace(/&amp;/g,'&').replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/&#x2F;/gi,'/').replace(/\\u0026/g,'&').replace(/\\\//g,'/');
const absolute=(href:string)=>!href?'':href.startsWith('//')?`https:${href}`:href.startsWith('http')?href:`https://www.obsbygg.no${href.startsWith('/')?'':'/'}${href}`;
const headers={'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/131 Safari/537.36','accept-language':'nb-NO,nb;q=0.9,en;q=0.7','accept':'text/html,application/xhtml+xml,application/json;q=0.9,*/*;q=0.8','referer':'https://www.obsbygg.no/'};
type Input={ean?:string;productName:string;productKey:string;supplier:string;size?:string;rawName?:string};
type Result={found:boolean;imageUrl?:string;displayName?:string;url?:string;category?:string;source?:string};
const cleanTitle=(title:string)=>decodeHtml(title).replace(/\s*[|–-]\s*Obs BYGG.*$/i,'').replace(/\s*\|\s*Coop.*$/i,'').trim();
async function persist(input:Input,result:Result){const q=sql();await ensureSchema();await q`INSERT INTO paint_products(product_key,display_name,supplier,size,ean,image_url,image_source,product_url,category,image_approved,aliases,updated_at) VALUES(${input.productKey},${result.displayName||input.productName},${input.supplier},${input.size||null},${input.ean||null},${result.imageUrl||null},${result.source||result.url||'automatic'},${result.url||null},${result.category||null},true,${JSON.stringify([input.productName,input.rawName].filter(Boolean))}::jsonb,now()) ON CONFLICT(product_key) DO UPDATE SET display_name=excluded.display_name,supplier=excluded.supplier,size=excluded.size,image_url=COALESCE(excluded.image_url,paint_products.image_url),image_source=excluded.image_source,product_url=COALESCE(excluded.product_url,paint_products.product_url),category=COALESCE(excluded.category,paint_products.category),image_approved=true,ean=COALESCE(excluded.ean,paint_products.ean),aliases=(SELECT jsonb_agg(DISTINCT x) FROM jsonb_array_elements(paint_products.aliases || excluded.aliases) x),updated_at=now()`;}
function productLinks(html:string){const links=new Set<string>();for(const rx of [/href=["']([^"']+\/\d{5,}(?:[?][^"']*)?)["']/gi,/"url"\s*:\s*"([^"]+\/\d{5,}[^"]*)"/gi,/"canonicalUrl"\s*:\s*"([^"]+)"/gi,/"productUrl"\s*:\s*"([^"]+)"/gi])for(const m of html.matchAll(rx)){const href=decodeHtml(m[1]);if(/obsbygg\.no|^\//i.test(href))links.add(absolute(href));}return [...links].filter(x=>/\/maling\//i.test(x)).slice(0,6);}
function images(html:string){const out:string[]=[];const add=(v?:string)=>{if(v){const u=absolute(decodeHtml(v.split(',')[0].trim().split(/\s+/)[0]));if(/^https?:\/\//.test(u))out.push(u)}};for(const rx of [/property=["']og:image(?::secure_url)?["'][^>]*content=["']([^"']+)/gi,/content=["']([^"']+)["'][^>]*property=["']og:image/gi,/"image"\s*:\s*\[?\s*"([^"]+)"/gi,/"imageUrl"\s*:\s*"([^"]+)"/gi,/(?:src|data-src)=["']([^"']*globalassets\/productimages\/[^"']+)["']/gi])for(const m of html.matchAll(rx))add(m[1]);return [...new Set(out)];}
async function fetchPage(url:string){try{const r=await fetch(url,{headers,cache:'no-store',redirect:'follow',signal:AbortSignal.timeout(14000)});if(!r.ok)return null;const html=await r.text();const image=images(html)[0];const title=cleanTitle(html.match(/property=["']og:title["'][^>]*content=["']([^"']+)/i)?.[1]||html.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i)?.[1]?.replace(/<[^>]+>/g,' ')||html.match(/<title>([^<]+)/i)?.[1]||'');return image?{image,title}:null}catch{return null}}
function score(title:string,input:Input){const a=title.toUpperCase(),b=`${input.productName} ${input.rawName||''}`.toUpperCase();let n=0;for(const word of b.replace(/[^A-ZÆØÅ0-9]+/g,' ').split(/\s+/).filter(x=>x.length>2))if(a.includes(word))n++;if(input.size&&a.includes(input.size.replace(' ','')))n+=2;return n;}
export async function findObsbyggImage(input:Input):Promise<Result>{await ensureSchema();const q=sql();const existing=await q`SELECT display_name,image_url,product_url,category FROM paint_products WHERE product_key=${input.productKey} LIMIT 1`;const known=catalogEntry(input.productName,input.rawName);if(existing[0]?.image_url){const result={found:true,imageUrl:existing[0].image_url,displayName:known?.name||existing[0].display_name,url:existing[0].product_url||known?.pageUrl,category:known?.category||existing[0].category,source:'database'};if(known?.name&&known.name!==existing[0].display_name)await persist(input,result);return result;}if(known?.image){const r={found:true,imageUrl:known.image,displayName:known.name,url:known.pageUrl,category:known.category,source:'catalog'};await persist(input,r);return r;}if(known?.pageUrl){const page=await fetchPage(known.pageUrl);if(page){const r={found:true,imageUrl:page.image,displayName:known.name,url:known.pageUrl,category:known.category,source:'catalog-page'};await persist(input,r);return r;}}const terms=[input.ean,`${input.productName} ${input.size||''}`,input.rawName].filter(Boolean) as string[];for(const term of [...new Set(terms)])for(const searchUrl of [`https://www.obsbygg.no/sok?q=${encodeURIComponent(term)}`,`https://www.obsbygg.no/sok?query=${encodeURIComponent(term)}`]){try{const r=await fetch(searchUrl,{headers,cache:'no-store',redirect:'follow',signal:AbortSignal.timeout(14000)});if(!r.ok)continue;const html=await r.text();const candidates=[] as {url:string;image:string;title:string;score:number}[];for(const url of productLinks(html)){const page=await fetchPage(url);if(page)candidates.push({url,image:page.image,title:page.title,score:score(page.title,input)});}candidates.sort((a,b)=>b.score-a.score);const best=candidates[0];if(best&&best.score>0){const result={found:true,imageUrl:best.image,displayName:best.title||input.productName,url:best.url,category:known?.category,source:'obsbygg-search'};await persist(input,result);return result;}}catch{}}const result={found:false,displayName:known?.name||input.productName,category:known?.category};await persist(input,result);return result;}
