import {NextResponse} from 'next/server';
import {isAdmin,isAuthenticated} from '@/lib/server/auth';
import {ensureSchema,sql} from '@/lib/server/db';
const DEFAULTS=[['interior','Tak'],['interior','Supermatt'],['interior','Matt'],['interior','Silkematt'],['interior','Tre & Panel'],['interior','Grunning'],['interior','Sparkel'],['interior','Lakk'],['terrace','Vanntynnet'],['terrace','Terrassemaling'],['terrace','Oljebasert'],['tools','Pensler'],['tools','Ruller'],['tools','Tape'],['tools','Tildekning'],['tools','Rensemidler'],['tools','Diverse'],['exterior','Maling / Dekkbeis / Beis'],['exterior','Vindu / Dør'],['exterior','Murmaling']] as const;
const areaMap:Record<string,string>={exterior:'exterior',eksterior:'exterior','eksteriør':'exterior','eksteriørmaling':'exterior',interior:'interior','interiør':'interior','interiørmaling':'interior',terrace:'terrace',terrasse:'terrace',tools:'tools',malerverktøy:'tools'};
const normalizeArea=(v:unknown)=>areaMap[String(v||'').trim().toLocaleLowerCase('nb-NO')]||String(v||'').trim();
async function seed(){const q=sql();for(const [area,name] of DEFAULTS)await q`INSERT INTO paint_tags(area,name,is_active) VALUES(${area},${name},true) ON CONFLICT(area,name) DO UPDATE SET is_active=true`}
export async function GET(){if(!(await isAuthenticated()))return NextResponse.json({error:'Ikke innlogget'},{status:401});try{await ensureSchema();await seed();const q=sql();const tags=await q`SELECT id::text,area,name,is_active FROM paint_tags WHERE is_active=true ORDER BY CASE area WHEN 'exterior' THEN 1 WHEN 'interior' THEN 2 WHEN 'terrace' THEN 3 ELSE 4 END,lower(name)`;return NextResponse.json({tags})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Kunne ikke hente tags'},{status:500})}}
export async function POST(req:Request){if(!(await isAdmin()))return NextResponse.json({error:'Kun Admin kan opprette tags.'},{status:403});try{await ensureSchema();const body=await req.json();const area=normalizeArea(body.area),name=String(body.name||'').trim();if(!['interior','terrace','tools','exterior'].includes(area)||!name)return NextResponse.json({error:'Gyldig område og navn kreves'},{status:400});const q=sql();const rows=await q`INSERT INTO paint_tags(area,name,is_active) VALUES(${area},${name},true) ON CONFLICT(area,name) DO UPDATE SET is_active=true,updated_at=now() RETURNING id::text,area,name,is_active`;return NextResponse.json({ok:true,tag:rows[0]})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Kunne ikke opprette tag'},{status:500})}}
export async function DELETE(req:Request){if(!(await isAdmin()))return NextResponse.json({error:'Kun Admin kan slette tags.'},{status:403});try{await ensureSchema();const {id}=await req.json();const q=sql();const tag=await q`SELECT area,name FROM paint_tags WHERE id=${id}::bigint`;if(!tag.length)return NextResponse.json({error:'Taggen finnes ikke'},{status:404});const used=await q`SELECT count(*)::int count FROM paint_products WHERE area=${tag[0].area} AND subgroup=${tag[0].name}`;if((used[0]?.count||0)>0)return NextResponse.json({error:'Taggen er i bruk. Flytt produktene før den slettes.'},{status:409});await q`UPDATE paint_tags SET is_active=false,updated_at=now() WHERE id=${id}::bigint`;return NextResponse.json({ok:true})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Kunne ikke slette tag'},{status:500})}}
