'use client';
import {useEffect,useState} from 'react';
import {CalendarDays,CheckCircle2,FileSpreadsheet,LoaderCircle,PackageSearch,Play,RefreshCw,Trash2,UploadCloud} from 'lucide-react';
import {parsePaintHistoryWorkbook} from '@/lib/parser';

async function json(res:Response){const text=await res.text();try{return text?JSON.parse(text):{}}catch{return {error:text||'Ugyldig serversvar'}}}
export default function ServerImportJobs({isAdmin,onImported}:{isAdmin:boolean;onImported:()=>Promise<void>}){
 const [file,setFile]=useState<File>();const [jobs,setJobs]=useState<any[]>([]);const [busy,setBusy]=useState('');const [status,setStatus]=useState('');
 const load=async()=>{const r=await fetch('/api/import-jobs',{cache:'no-store'}),j=await json(r);if(r.ok)setJobs(j.jobs||[])};
 useEffect(()=>{load()},[]);
 const stage=async()=>{if(!file)return;setBusy('stage');setStatus('Leser årsfilen lokalt …');try{const reports=await parsePaintHistoryWorkbook(file);const create=await fetch('/api/import-jobs',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({sourceName:file.name,totalDays:reports.length})}),cj=await json(create);if(!create.ok)throw new Error(cj.error);for(let i=0;i<reports.length;i++){setStatus(`Lagrer rapportdag ${i+1} av ${reports.length} på serveren …`);const r=await fetch(`/api/import-jobs/${cj.id}/stage-day`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({report:reports[i]})}),j=await json(r);if(!r.ok)throw new Error(j.error)}setStatus('Filen er lagret som en serverjobb. Du kan fortsette fra en annen enhet.');setFile(undefined);await load()}catch(e){setStatus(e instanceof Error?e.message:'Kunne ikke opprette serverjobb')}finally{setBusy('')}};
 const run=async(id:string,mode:'sync-next'|'import-next')=>{setBusy(`${mode}-${id}`);try{for(let i=0;i<100000;i++){const r=await fetch(`/api/import-jobs/${id}/${mode}`,{method:'POST'}),j=await json(r);if(!r.ok)throw new Error(j.error);if(j.done)break;if(i%5===0)await load()}setStatus(mode==='sync-next'?'Produktsynkroniseringen er ferdig.':'Rapportdagene er importert.');await load();if(mode==='import-next')await onImported()}catch(e){setStatus(e instanceof Error?e.message:'Operasjonen stoppet. Fremdriften er lagret.')}finally{setBusy('')}};
 const remove=async(id:string)=>{if(!confirm('Slette denne serverlagrede importjobben?'))return;await fetch(`/api/import-jobs/${id}`,{method:'DELETE'});await load()};
 return <section className="panel serverImportJobs"><div className="panelHead"><div><span className="eyebrow">SERVERLAGRET IMPORT</span><h2>Fortsett importen fra PC eller mobil</h2><p className="panelIntro">Årsfilen deles i rapportdager og lagres i Neon. Produktsynkronisering og rapportimport kan deretter startes senere fra en annen enhet.</p></div><button className="secondary" onClick={load}><RefreshCw size={16}/>Oppdater</button></div><div className="serverJobUpload"><label className="drop"><UploadCloud/><b>{file?.name||'Velg stor historikkfil'}</b><span>Filen må først leses og lagres som en serverjobb</span><input type="file" accept=".xlsx,.xls" onChange={e=>setFile(e.target.files?.[0])}/></label><button className="primary" disabled={!file||Boolean(busy)} onClick={stage}>{busy==='stage'?<LoaderCircle className="spin"/>:<FileSpreadsheet/>}Last opp og lagre serverjobb</button></div>{status&&<div className="check"><CheckCircle2/><div><b>Status</b><span>{status}</span></div></div>}<div className="serverJobList">{jobs.map(job=><article key={job.id} className="serverJobCard"><header><div><b>{job.source_name}</b><span>Opprettet av {job.created_by||'ukjent'}</span></div><small>{job.status}</small></header><div className="serverJobProgress"><span><PackageSearch/>Produkter <b>{job.synced_products}/{job.total_products}</b></span><span><CalendarDays/>Rapportdager <b>{job.imported_days}/{job.total_days}</b></span><span>Lagret <b>{job.staged_days}/{job.total_days}</b></span></div><div className="serverJobActions"><button className="secondary" disabled={Boolean(busy)||job.staged_days<job.total_days} onClick={()=>run(job.id,'sync-next')}><Play size={15}/>{busy===`sync-next-${job.id}`?'Synkroniserer …':'Synkroniser produkter nå'}</button><button className="successBtn" disabled={Boolean(busy)||job.staged_days<job.total_days} onClick={()=>run(job.id,'import-next')}><CheckCircle2 size={15}/>{busy===`import-next-${job.id}`?'Importerer …':'Importer rapportdager'}</button>{isAdmin&&<button className="dangerBtn iconOnly" onClick={()=>remove(job.id)}><Trash2 size={16}/></button>}</div></article>)}{!jobs.length&&<div className="empty"><CalendarDays/><p>Ingen serverlagrede importjobber.</p></div>}</div></section>
}
